
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 29 07:31:03 IRDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Constants {
  /* terminals */
  public static final int DIVIDE = 31;
  public static final int STRING_LITERAL = 37;
  public static final int UMINUS = 29;
  public static final int FEATURE = 4;
  public static final int INTEGER = 36;
  public static final int SMALLER = 25;
  public static final int LPAREN = 33;
  public static final int GREATER = 23;
  public static final int MINUS = 28;
  public static final int RPAREN = 34;
  public static final int SEMICOLON = 20;
  public static final int COMMA = 21;
  public static final int SMALLER_EQUAL = 26;
  public static final int CLASS = 2;
  public static final int UNTIL = 13;
  public static final int LOOP = 14;
  public static final int PLUS = 27;
  public static final int ASSIGN = 18;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int EQUAL = 22;
  public static final int STRING_TYPE = 6;
  public static final int TRUE = 16;
  public static final int GREATER_EQUAL = 24;
  public static final int error = 1;
  public static final int MOD = 32;
  public static final int INTEGER_TYPE = 5;
  public static final int FROM = 12;
  public static final int TIMES = 30;
  public static final int COLON = 19;
  public static final int ELSE = 11;
  public static final int CREATE = 3;
  public static final int THEN = 10;
  public static final int END = 8;
  public static final int FALSE = 17;
  public static final int PRINT = 15;
  public static final int DO = 7;
  public static final int IDENTIFIER = 35;
}

