
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 02 23:25:34 IRDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Constants {
  /* terminals */
  public static final int TIMES = 27;
  public static final int SMALLER_EQUAL = 23;
  public static final int MOD = 29;
  public static final int FROM = 11;
  public static final int CLASS = 2;
  public static final int ELSE = 10;
  public static final int PLUS = 24;
  public static final int RPAREN = 31;
  public static final int SMALLER = 22;
  public static final int EQUAL = 19;
  public static final int THEN = 9;
  public static final int LOOP = 13;
  public static final int IDENTIFIER = 32;
  public static final int END = 7;
  public static final int GREATER_EQUAL = 21;
  public static final int GREATER = 20;
  public static final int TRUE = 15;
  public static final int IF = 8;
  public static final int LPAREN = 30;
  public static final int COLON = 18;
  public static final int STRING_LITERAL = 34;
  public static final int DO = 6;
  public static final int CREATE = 3;
  public static final int INTEGER_TYPE = 5;
  public static final int EOF = 0;
  public static final int DIVIDE = 28;
  public static final int MINUS = 25;
  public static final int FALSE = 16;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int ASSIGN = 17;
  public static final int UNTIL = 12;
  public static final int INTEGER = 33;
  public static final int FEATURE = 4;
  public static final int UMINUS = 26;
}

