/* The following code was generated by JFlex 1.6.1 */

/**********************************************************************
* Compiler Project – Phase 2                                          *
* Language : Eiffel                                                   *
* Team :                                                              *
*   1. Sadra Samadi             - 9312268122                          *
*   2. Hamid Hosseini Nejad     - 9312268110                          *
***********************************************************************/

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Data/IdeaProjects/compiler/res/eiffel.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\1\0\1\5\1\3\22\0\1\5\1\0\1\53"+
    "\2\0\1\50\2\0\1\51\1\52\1\46\1\45\1\0\1\12\1\0"+
    "\1\47\1\6\11\2\1\41\1\0\1\44\1\42\1\43\2\0\4\10"+
    "\1\27\1\10\1\30\1\1\1\24\4\1\1\25\3\1\1\31\1\1"+
    "\1\26\3\1\1\7\2\1\1\0\1\54\2\0\1\11\1\0\1\15"+
    "\1\10\1\13\1\32\1\20\1\22\1\1\1\36\1\35\2\1\1\14"+
    "\1\37\1\34\1\33\1\40\1\1\1\17\1\16\1\21\1\23\2\1"+
    "\1\7\2\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff95\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\2\4\1\3\1\5\12\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\0\1\4"+
    "\14\2\1\24\1\25\1\2\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\3\4\2\1\35\12\2\1\36"+
    "\1\37\1\40\1\41\1\2\1\42\4\2\1\43\1\2"+
    "\1\44\1\2\1\45\1\2\1\46\1\47\2\2\1\50"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\132\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\132\0\u0357\0\u0384\0\132"+
    "\0\132\0\132\0\132\0\132\0\132\0\132\0\u03b1\0\132"+
    "\0\u03de\0\u040b\0\u0438\0\u0465\0\u0492\0\u04bf\0\u04ec\0\u0519"+
    "\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654\0\207"+
    "\0\207\0\u0681\0\132\0\132\0\132\0\132\0\132\0\132"+
    "\0\132\0\u040b\0\u06ae\0\u06db\0\u0708\0\u0735\0\207\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca"+
    "\0\u08f7\0\207\0\207\0\207\0\207\0\u0924\0\207\0\u0951"+
    "\0\u097e\0\u09ab\0\u09d8\0\207\0\u0a05\0\207\0\u0a32\0\207"+
    "\0\u0a5f\0\207\0\207\0\u0a8c\0\u0ab9\0\207\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\7\1\10\2\4\1\3"+
    "\1\11\1\12\1\13\3\4\1\14\1\15\1\16\1\17"+
    "\1\20\5\4\1\21\2\4\1\22\2\4\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\3\3\37\2\3\46\37\1\40\1\41"+
    "\56\0\2\4\3\0\4\4\1\0\26\4\16\0\1\5"+
    "\3\0\1\5\52\0\1\7\52\0\1\5\3\0\1\5"+
    "\1\42\57\0\1\43\43\0\2\4\3\0\4\4\1\0"+
    "\1\4\1\44\2\4\1\45\21\4\15\0\2\4\3\0"+
    "\4\4\1\0\20\4\1\46\5\4\15\0\2\4\3\0"+
    "\4\4\1\0\1\4\1\47\17\4\1\50\4\4\15\0"+
    "\2\4\3\0\4\4\1\0\4\4\1\51\16\4\1\52"+
    "\2\4\15\0\2\4\3\0\4\4\1\0\2\4\1\53"+
    "\1\4\1\54\1\55\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\21\4\1\56\4\4\15\0\2\4\3\0\4\4"+
    "\1\0\12\4\1\57\13\4\15\0\2\4\3\0\4\4"+
    "\1\0\20\4\1\60\5\4\15\0\2\4\3\0\4\4"+
    "\1\0\7\4\1\61\16\4\15\0\2\4\3\0\4\4"+
    "\1\0\4\4\1\62\21\4\56\0\1\63\54\0\1\64"+
    "\54\0\1\65\12\0\3\37\2\0\46\37\21\0\1\66"+
    "\1\0\1\67\12\0\1\70\16\0\1\71\3\0\1\72"+
    "\3\0\1\72\1\0\1\72\2\0\1\72\1\0\1\72"+
    "\2\0\1\72\1\0\1\72\4\0\1\72\2\0\1\72"+
    "\22\0\3\43\1\6\1\7\50\43\1\0\2\4\3\0"+
    "\4\4\1\0\2\4\1\73\23\4\15\0\2\4\3\0"+
    "\4\4\1\0\5\4\1\74\20\4\15\0\2\4\3\0"+
    "\4\4\1\0\20\4\1\75\5\4\15\0\2\4\3\0"+
    "\4\4\1\0\3\4\1\76\22\4\15\0\2\4\3\0"+
    "\4\4\1\0\17\4\1\77\6\4\15\0\2\4\3\0"+
    "\4\4\1\0\10\4\1\100\15\4\15\0\2\4\3\0"+
    "\4\4\1\0\5\4\1\101\20\4\15\0\2\4\3\0"+
    "\4\4\1\0\1\4\1\102\24\4\15\0\2\4\3\0"+
    "\4\4\1\0\20\4\1\103\5\4\15\0\2\4\3\0"+
    "\4\4\1\0\2\4\1\104\23\4\15\0\2\4\3\0"+
    "\4\4\1\0\6\4\1\105\17\4\15\0\2\4\3\0"+
    "\4\4\1\0\13\4\1\106\12\4\15\0\2\4\3\0"+
    "\4\4\1\0\22\4\1\107\3\4\15\0\2\4\3\0"+
    "\4\4\1\0\3\4\1\110\22\4\15\0\2\4\3\0"+
    "\4\4\1\0\2\4\1\111\23\4\15\0\2\4\3\0"+
    "\4\4\1\0\25\4\1\112\15\0\2\4\3\0\4\4"+
    "\1\0\5\4\1\113\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\5\4\1\114\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\21\4\1\115\4\4\15\0\2\4\3\0\4\4"+
    "\1\0\3\4\1\116\22\4\15\0\2\4\3\0\4\4"+
    "\1\0\24\4\1\117\1\4\15\0\2\4\3\0\4\4"+
    "\1\0\6\4\1\120\17\4\15\0\2\4\3\0\4\4"+
    "\1\0\22\4\1\121\3\4\15\0\2\4\3\0\4\4"+
    "\1\0\14\4\1\122\11\4\15\0\2\4\3\0\4\4"+
    "\1\0\21\4\1\123\4\4\15\0\2\4\3\0\4\4"+
    "\1\0\3\4\1\124\22\4\15\0\2\4\3\0\4\4"+
    "\1\0\6\4\1\125\17\4\15\0\2\4\3\0\4\4"+
    "\1\0\5\4\1\126\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\10\4\1\127\15\4\15\0\2\4\3\0\4\4"+
    "\1\0\1\4\1\130\24\4\15\0\2\4\3\0\4\4"+
    "\1\0\15\4\1\131\10\4\15\0\2\4\3\0\4\4"+
    "\1\0\6\4\1\132\17\4\15\0\2\4\3\0\4\4"+
    "\1\0\5\4\1\133\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\4\4\1\134\21\4\15\0\2\4\3\0\4\4"+
    "\1\0\14\4\1\135\11\4\15\0\2\4\3\0\4\4"+
    "\1\0\5\4\1\136\20\4\15\0\2\4\3\0\4\4"+
    "\1\0\16\4\1\137\7\4\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2790];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\15\1\1\11\2\1\7\11"+
    "\1\1\1\11\1\1\1\0\20\1\7\11\46\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbol(Constants.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal Character <" + yytext() + "> at line " + (yyline + 1) + ", column " + (yycolumn + 1));
            }
          case 42: break;
          case 2: 
            { return symbol(Constants.IDENTIFIER, yytext());
            }
          case 43: break;
          case 3: 
            { return symbol(Constants.INTEGER, new Integer(yytext()));
            }
          case 44: break;
          case 4: 
            { /* Do nothing ... */
            }
          case 45: break;
          case 5: 
            { return symbol(Constants.MINUS);
            }
          case 46: break;
          case 6: 
            { return symbol(Constants.COLON);
            }
          case 47: break;
          case 7: 
            { return symbol(Constants.EQUAL);
            }
          case 48: break;
          case 8: 
            { return symbol(Constants.GREATER);
            }
          case 49: break;
          case 9: 
            { return symbol(Constants.SMALLER);
            }
          case 50: break;
          case 10: 
            { return symbol(Constants.PLUS);
            }
          case 51: break;
          case 11: 
            { return symbol(Constants.TIMES);
            }
          case 52: break;
          case 12: 
            { return symbol(Constants.DIVIDE);
            }
          case 53: break;
          case 13: 
            { return symbol(Constants.MOD);
            }
          case 54: break;
          case 14: 
            { return symbol(Constants.LPAREN);
            }
          case 55: break;
          case 15: 
            { return symbol(Constants.RPAREN);
            }
          case 56: break;
          case 16: 
            { string.setLength(0); yybegin(STRING);
            }
          case 57: break;
          case 17: 
            { string.append(yytext());
            }
          case 58: break;
          case 18: 
            { yybegin(YYINITIAL); return symbol(Constants.STRING_LITERAL, string.toString());
            }
          case 59: break;
          case 19: 
            { string.append('\\');
            }
          case 60: break;
          case 20: 
            { return symbol(Constants.DO);
            }
          case 61: break;
          case 21: 
            { return symbol(Constants.IF);
            }
          case 62: break;
          case 22: 
            { return symbol(Constants.ASSIGN);
            }
          case 63: break;
          case 23: 
            { return symbol(Constants.GREATER_EQUAL);
            }
          case 64: break;
          case 24: 
            { return symbol(Constants.SMALLER_EQUAL);
            }
          case 65: break;
          case 25: 
            { string.append('\r');
            }
          case 66: break;
          case 26: 
            { string.append('\t');
            }
          case 67: break;
          case 27: 
            { string.append('\n');
            }
          case 68: break;
          case 28: 
            { string.append('\"');
            }
          case 69: break;
          case 29: 
            { return symbol(Constants.END);
            }
          case 70: break;
          case 30: 
            { return symbol(Constants.LOOP);
            }
          case 71: break;
          case 31: 
            { return symbol(Constants.ELSE);
            }
          case 72: break;
          case 32: 
            { return symbol(Constants.TRUE);
            }
          case 73: break;
          case 33: 
            { return symbol(Constants.THEN);
            }
          case 74: break;
          case 34: 
            { return symbol(Constants.FROM);
            }
          case 75: break;
          case 35: 
            { return symbol(Constants.CLASS);
            }
          case 76: break;
          case 36: 
            { return symbol(Constants.FALSE);
            }
          case 77: break;
          case 37: 
            { return symbol(Constants.UNTIL);
            }
          case 78: break;
          case 38: 
            { return symbol(Constants.PRINT);
            }
          case 79: break;
          case 39: 
            { return symbol(Constants.CREATE);
            }
          case 80: break;
          case 40: 
            { return symbol(Constants.FEATURE);
            }
          case 81: break;
          case 41: 
            { return symbol(Constants.INTEGER_TYPE);
            }
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
